// Code generated by "stringer -type=Seed ./src/msdb5/card.go"; DO NOT EDIT.
package card

import "strconv"

func (card Card) String() string {
	return "(" + strconv.Itoa(int(card.number)) + " of " + card.seed.String() + ")"
}
