// Code generated by "stringer -type=Seed ./src/msdb5/card.go"; DO NOT EDIT.
package card

import "strconv"

func (card ID) String() string {
	return "(" + strconv.Itoa(int(card.ToNumber())) + " of " + card.ToSeed().String() + ")"
}
